# Generated by Django 4.1.3 on 2022-11-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host_id',
            new_name='host',
        ),
    ]
